baseURL = 'https://campioniman.github.io/'
languageCode = 'en-us'
title = 'Daniel Campioni'
theme = 'blist'

[params]
    author = 'Daniel Campioni'
    description = 'The latest news on my professional carrer'

    [[params.social]]
        icon = "github"
        name = "GitHub"
        url = "https://github.com/CampioniMan"
